name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18
        package-manager: pnpm
    - name: Install dependencies
      run: pnpm install
    - name: Build project
      run: pnpm build
    - name: Run tests
      run: pnpm test